project:
  type: website
  resources: 
    - "*.mp4"

format:
  html:
    theme: lumen
    toc: true
    link-external-newwindow: true

website:
  navbar: 
    search: true
    left:
      - text: "Our Vision/Data Prep"
        href: index.ipynb
      - text: "Model 1"
        href:  model_1.ipynb
      - text: "Model 2"
        href: model_2.ipynb
      - text: "RAG"
        href: rag.ipynb
      - text: "Future Work"
        href: future_work.ipynb
      - text: "Demo and Conclusion"
        href: conclusion.ipynb
  
    tools: 
      - icon: github
        url: https://github.com/hannah-hana-kim/DSAN-6725-writeup/tree/main
      
    title: "CASUAL.AI"

  favicon: images/vita.png

bibliography: references.bib
